project_name             = "3tier"
region                   = "us-east-1"
azs                      = ["us-east-1a", "us-east-1b"]
vpc_cidr                 = "10.0.0.0/16"
public_subnets           = ["10.0.1.0/24", "10.0.2.0/24"]
public_subnet_names      = ["public-web-subnet-1", "public-web-subnet-2"]
private_subnet_names     = ["private-app-subnet-1", "private-app-subnet-2", "private-db-subnet-1", "private-db-subnet-2"]
private_subnets          = ["10.0.3.0/24", "10.0.4.0/24", "10.0.5.0/24", "10.0.6.0/24"]
identifier               = "tier3-db"
storage                  = "20"
engine                   = "aurora-mysql"
engine_version           = "8.0.mysql_aurora.3.07.1"
instance_class           = "db.t3.medium"
db_name                  = "mydb"
db_username              = "admin"
db_password              = "password"
app_instance_type        = "t2.micro"
web_instance_type        = "t2.micro"
web_asg_desired_capacity = 1
web_asg_min_size         = 1
web_asg_max_size         = 1
app_asg_desired_capacity = 1
app_asg_min_size         = 1
app_asg_max_size         = 1